### ISSUE TITLE
Error "No objects to concatenate" when trying to run script

### ISSUE THREAD

**Issue by yochannah** [JohnBurant/COVID19-Model-Power-Ratings#2]
I've set up the code locally by [editing these two lines](https://github.com/yochannah/COVID19-Model-Power-Ratings/blob/debug/power_ratings_v0.3.py#L21-L22) and installed missing libraries as I was prompted - any idea what I've done wrong or what I'm missing? I'm reasonably certain the paths I set are correct. 

```bash
Beginning generation of power ratings from raw evaluation files.
Datestamp: 2020-09-27
Following these policies:
  include_baselines: True
  include_ensemble: True
  include_models_without_full_measure_set: False
  include_models_without_all_weeks: False
  generate_partial_results_for_recent_weeks: False
  num_forecasts_for_lifetime_list_eligibility: 4
Measures used: states_abs_errs, states_sq_errs, states_mean_ranks, us_errs
Loading evaluation files...Done
Number of possible week-pair files: 760
Number of files processed: 0
Traceback (most recent call last):
  File "power_ratings_v0.3.py", line 132, in <module>
    df_raw = pd.concat(l_dfs,axis=1)
  File "/Users/yoyehudi/opt/anaconda3/envs/py37-backup/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    sort=sort,
  File "/Users/yoyehudi/opt/anaconda3/envs/py37-backup/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

```

**Comment by JohnBurant** [comment]
I notice the line "Number of files processed: 0" in the output, which would happen if l_dfs is an empty list. This would happen if the code didn't find any files to read in. 

This could happen if there isn't a trailing slash at the end of the directory indicated in yyg_repo_dir.
This could also happen if the week periods specified don't correspond to files to exist.

Wild guess... the first issue?

**Comment by yochannah** [comment]
hmmm, added trailing slashes, still the same error. 

I have a fresh copy of master from the https://github.com/youyanggu/covid19-forecast-hub-evaluation repo checked out today - presumably the default week format _should_ be okay?
